# Generated by Django 5.1.7 on 2025-03-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_to_done",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Время на выполнение (в минутах)"
            ),
        ),
    ]
