# Generated by Django 5.1.7 on 2025-03-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.IntegerField(
                blank=True,
                choices=[("day", "Ежедневно"), ("week", "Еженедельно")],
                null=True,
                verbose_name="Периодичность",
            ),
        ),
    ]
